In [1]:
import xlsxwriter
import re
import numpy as np
import glob
import math

In [13]:
def text_to_excel(ang,sigma,txt):
    print("newcross10Mev/doublediff_cossat{1}_*.txt".format(txt,ang,sigma))
    mylist = [f for f in glob.glob("./Tritonnewcross/{0}doublediff_cossat{1}_*.txt".format(txt,ang,sigma))]
    print(mylist)
    
    workbook = xlsxwriter.Workbook('{0}Proton{1}.xlsx'.format(txt,ang,sigma))
    worksheet = workbook.add_worksheet("Proton")
    worksheet1 = workbook.add_worksheet("Deuteron")
    worksheet2 = workbook.add_worksheet("Triton")
    worksheet3 = workbook.add_worksheet("Pion")
    row=2
    col=0
    i=1
    for file in mylist:
        row=2
        sig =re.split("_",file)
        #print(sig[2])
        f = open(file, 'r')
        for line in f:
        #print(line)
            if(re.match(r"Proton",line)):
                worksheet.write('A1', line)
            elif(re.match(r"Deuteron",line)):
                break
            else:
                sp =re.split(" |\n",line)
                flag2= not math.isnan(float(sp[3]))
                #print(sp)
                if(col==0and flag2):
                    worksheet.write(1, col,"Energy" )
                    worksheet.write(row, col,     sp[0])
                if(flag2):
                    worksheet.write(1, col+1,f"Cross_sec{sig[2]}" )
                    worksheet.write(1, col+2,f"StatErr{sig[2]}" )
                    worksheet.write(1, col+3,f"EffErr{sig[2]}" )
                    worksheet.write(row, col + 1, sp[1])
                    worksheet.write(row, col + 2, sp[2])
                    worksheet.write(row, col + 3, sp[3])
                    row += 1
        row=2
        for line in f:
            worksheet1.write('A1', "Deuteron")
            if(re.match(r"triton",line)):
                break
            else:
                sp =re.split(" |\n",line)
                flag2= not math.isnan(float(sp[2]))
                #print(sp)
                if(col==0and flag2): 
                    worksheet1.write(1, col,"Energy" )
                    worksheet1.write(row, col,     sp[0])
                if(flag2):
                    worksheet1.write(1, col+1,f"Cross_sec{sig[2]}" )
                    worksheet1.write(1, col+2,f"StatErr{sig[2]}" )
                    worksheet1.write(1, col+3,f"EffErr{sig[2]}" )
                    worksheet1.write(row, col + 1, sp[1])
                    worksheet1.write(row, col + 2, sp[2])
                    worksheet1.write(row, col + 3, sp[3])
                    row += 1
        row=2
        for line in f:
            worksheet2.write('A1', "Triton")
            if(re.match(r"pion",line)):
                break
            else:
                sp =re.split(" |\n",line)
                flag2= not math.isnan(float(sp[2]))
                #print(sp)
                if(col==0and flag2): 
                    worksheet2.write(1, col,"Energy" )
                    worksheet2.write(row, col,     sp[0])
                if(flag2):
                    worksheet2.write(1, col+1,f"Cross_sec{sig[2]}" )
                    worksheet2.write(1, col+2,f"StatErr{sig[2]}" )
                    worksheet2.write(1, col+3,f"EffErr{sig[2]}" )
                    worksheet2.write(row, col + 1, sp[1])
                    worksheet2.write(row, col + 2, sp[2])
                    worksheet2.write(row, col + 3, sp[3])
                    row += 1
        row=2
        for line in f:
            worksheet3.write('A1', "Pion")
            if(re.match(r"triton",line)):
                break
            else:
                sp =re.split(" |\n",line)
                flag2= not math.isnan(float(sp[3]))
                #print(sp)
                if(col==0and flag2): 
                    worksheet3.write(1, col,"Energy" )
                    worksheet3.write(row, col,     sp[0])
                if(flag2):
                    worksheet3.write(1, col+1,f"Cross_sec{sig[2]}" )
                    worksheet3.write(1, col+2,f"StatErr{sig[2]}" )
                    worksheet3.write(1, col+3,f"EffErr{sig[2]}" )
                    worksheet3.write(row, col + 1, sp[1])
                    worksheet3.write(row, col + 2, sp[2])
                    worksheet3.write(row, col + 3, sp[3])
                    row += 1
        col+=3
        i=i+1
    workbook.close()

In [14]:
INCL=""
sigma=0.6
for ang in [20,25,30,35,40,45,50,55,60,65,70,75,80]:
    text_to_excel(ang,sigma,INCL)

newcross10Mev/doublediff_cossat20_*.txt
['./Tritonnewcross\\doublediff_cossat20_0.6_new.txt', './Tritonnewcross\\doublediff_cossat20_0.8_new.txt', './Tritonnewcross\\doublediff_cossat20_1.0_new.txt', './Tritonnewcross\\doublediff_cossat20_1.2_new.txt', './Tritonnewcross\\doublediff_cossat20_1.5_new.txt', './Tritonnewcross\\doublediff_cossat20_1.8_new.txt']
newcross10Mev/doublediff_cossat25_*.txt
['./Tritonnewcross\\doublediff_cossat25_0.6_new.txt', './Tritonnewcross\\doublediff_cossat25_0.8_new.txt', './Tritonnewcross\\doublediff_cossat25_1.0_new.txt', './Tritonnewcross\\doublediff_cossat25_1.2_new.txt', './Tritonnewcross\\doublediff_cossat25_1.5_new.txt', './Tritonnewcross\\doublediff_cossat25_1.8_new.txt']
newcross10Mev/doublediff_cossat30_*.txt
['./Tritonnewcross\\doublediff_cossat30_0.6_new.txt', './Tritonnewcross\\doublediff_cossat30_0.8_new.txt', './Tritonnewcross\\doublediff_cossat30_1.0_new.txt', './Tritonnewcross\\doublediff_cossat30_1.2_new.txt', './Tritonnewcross\\doublediff_cossat30_1.5_new.txt', './Tritonnewcross\\doublediff_cossat30_1.8_new.txt']
newcross10Mev/doublediff_cossat35_*.txt
['./Tritonnewcross\\doublediff_cossat35_0.6_new.txt', './Tritonnewcross\\doublediff_cossat35_0.8_new.txt', './Tritonnewcross\\doublediff_cossat35_1.0_new.txt', './Tritonnewcross\\doublediff_cossat35_1.2_new.txt', './Tritonnewcross\\doublediff_cossat35_1.5_new.txt', './Tritonnewcross\\doublediff_cossat35_1.8_new.txt']
newcross10Mev/doublediff_cossat40_*.txt
['./Tritonnewcross\\doublediff_cossat40_0.6_new.txt', './Tritonnewcross\\doublediff_cossat40_0.8_new.txt', './Tritonnewcross\\doublediff_cossat40_1.0_new.txt', './Tritonnewcross\\doublediff_cossat40_1.2_new.txt', './Tritonnewcross\\doublediff_cossat40_1.5_new.txt', './Tritonnewcross\\doublediff_cossat40_1.8_new.txt']
newcross10Mev/doublediff_cossat45_*.txt
['./Tritonnewcross\\doublediff_cossat45_0.6_new.txt', './Tritonnewcross\\doublediff_cossat45_0.8_new.txt', './Tritonnewcross\\doublediff_cossat45_1.0_new.txt', './Tritonnewcross\\doublediff_cossat45_1.2_new.txt', './Tritonnewcross\\doublediff_cossat45_1.5_new.txt', './Tritonnewcross\\doublediff_cossat45_1.8_new.txt']
newcross10Mev/doublediff_cossat50_*.txt
['./Tritonnewcross\\doublediff_cossat50_0.6_new.txt', './Tritonnewcross\\doublediff_cossat50_0.8_new.txt', './Tritonnewcross\\doublediff_cossat50_1.0_new.txt', './Tritonnewcross\\doublediff_cossat50_1.2_new.txt', './Tritonnewcross\\doublediff_cossat50_1.5_new.txt', './Tritonnewcross\\doublediff_cossat50_1.8_new.txt']
newcross10Mev/doublediff_cossat55_*.txt
['./Tritonnewcross\\doublediff_cossat55_0.6_new.txt', './Tritonnewcross\\doublediff_cossat55_0.8_new.txt', './Tritonnewcross\\doublediff_cossat55_1.0_new.txt', './Tritonnewcross\\doublediff_cossat55_1.2_new.txt', './Tritonnewcross\\doublediff_cossat55_1.5_new.txt', './Tritonnewcross\\doublediff_cossat55_1.8_new.txt']
newcross10Mev/doublediff_cossat60_*.txt
['./Tritonnewcross\\doublediff_cossat60_0.6_new.txt', './Tritonnewcross\\doublediff_cossat60_0.8_new.txt', './Tritonnewcross\\doublediff_cossat60_1.0_new.txt', './Tritonnewcross\\doublediff_cossat60_1.2_new.txt', './Tritonnewcross\\doublediff_cossat60_1.5_new.txt', './Tritonnewcross\\doublediff_cossat60_1.8_new.txt']
newcross10Mev/doublediff_cossat65_*.txt
['./Tritonnewcross\\doublediff_cossat65_0.6_new.txt', './Tritonnewcross\\doublediff_cossat65_0.8_new.txt', './Tritonnewcross\\doublediff_cossat65_1.0_new.txt', './Tritonnewcross\\doublediff_cossat65_1.2_new.txt', './Tritonnewcross\\doublediff_cossat65_1.5_new.txt', './Tritonnewcross\\doublediff_cossat65_1.8_new.txt']
newcross10Mev/doublediff_cossat70_*.txt
['./Tritonnewcross\\doublediff_cossat70_0.6_new.txt', './Tritonnewcross\\doublediff_cossat70_0.8_new.txt', './Tritonnewcross\\doublediff_cossat70_1.0_new.txt', './Tritonnewcross\\doublediff_cossat70_1.2_new.txt', './Tritonnewcross\\doublediff_cossat70_1.5_new.txt', './Tritonnewcross\\doublediff_cossat70_1.8_new.txt']
newcross10Mev/doublediff_cossat75_*.txt
['./Tritonnewcross\\doublediff_cossat75_0.6_new.txt', './Tritonnewcross\\doublediff_cossat75_0.8_new.txt', './Tritonnewcross\\doublediff_cossat75_1.0_new.txt', './Tritonnewcross\\doublediff_cossat75_1.2_new.txt', './Tritonnewcross\\doublediff_cossat75_1.5_new.txt', './Tritonnewcross\\doublediff_cossat75_1.8_new.txt']
newcross10Mev/doublediff_cossat80_*.txt
['./Tritonnewcross\\doublediff_cossat80_0.6_new.txt', './Tritonnewcross\\doublediff_cossat80_0.8_new.txt', './Tritonnewcross\\doublediff_cossat80_1.0_new.txt', './Tritonnewcross\\doublediff_cossat80_1.2_new.txt', './Tritonnewcross\\doublediff_cossat80_1.5_new.txt', './Tritonnewcross\\doublediff_cossat80_1.8_new.txt']

In [17]:
import pandas as pd
import numpy as np
import re
uplimit=[[3000,3150,3150,3150,3150,3150,3150,3150,3000,3010,3000,3000,3000,3000,3000],[850,850,820,820,820,820,820,820,850,450,350],[400,400,400,400,400,400,400,400,450,450,450,450,450,450],[800,800,800,800,800,800,600,600,800,850,850,850]]
Particles = [
  "Proton",
  "Deuteron",
  "Triton",
  "PionPositive"
]
pd.set_option('precision', 4)
def read_excel(file,sheet,ang):
    print(file)
    upl=uplimit[sheet]
    if ang==25:
        up=upl[0]
    elif ang==35:
        up=upl[1]
    elif ang==65:
        up=upl[2]
    else:
        up=upl[3]
    particle=Particles[sheet]
    sp =re.split("\.",file)
    print(sp[0])
    df=pd.read_excel(file,skiprows=1,sheet_name=sheet)
    headers=["Energy","Sector1","Error 1","Sector2","Error 2","Sector3","Error 3","Sector4","Error 4","Sector5","Error 5","Sector6","Error 6"]
    df2=pd.read_excel(f"../crossparticle/{sp[0]}_1.0.xlsx",header=None,skiprows=1,sheet_name=sheet)
    df2=df2.loc[:,0:12]
    df2.columns=headers
    
    df=df[df['Energy']>40]
    df2=df2[df2['Energy']>40]
    df=df[df['Energy']<up]
    df2=df2[df2['Energy']<up]
    df2["Mean"]=df2.iloc[:,1::2].mean(axis=1)
    df = df.replace(0, np.nan)
    df2=df2.dropna()
    if(sheet==2 or sheet==3 or sheet==1):
        df=df.iloc[:,0:9]
    df.dropna(inplace=True)
    df2.dropna(inplace=True)
    df.reset_index(drop=True, inplace=True)
    df2.reset_index(drop=True, inplace=True)
    df2["Abs"]=np.abs(df2.iloc[:,1]-df2['Mean'])
    for i in range(3,12,2):
        df2["Abs"]+=np.abs(df2.iloc[:,i]-df2['Mean'])
    df2["Abs"]=df2["Abs"]/12
    df2["Per"]=(df2["Abs"]/df2['Mean'])*100
    df['Mean']=df.iloc[:,1::3].mean(axis=1)
    df['PIDerr']=df.iloc[:,1::3].std(axis=1)
    df3=df[["Energy","Mean","PIDerr","StatErr0.6","EffErr0.6"]]
    df3=pd.concat([df3, df2['Abs']], axis=1, sort=False)
    df3.dropna(inplace=True)
    df3.rename(columns = {'Mean':'Cross Section','Abs':'SectorErr','StatErr0.6':'StatErr','EffErr0.6':'EffError'}, inplace = True)
    df3["SysErr"]=np.sqrt(df3.iloc[:,2]**2+df3.iloc[:,3]**2+df3.iloc[:,4]**2)
    df4=df3[['Energy','Cross Section','SysErr','StatErr']]
    df4.drop(df4[df4['Cross Section'] < df4['SysErr']].index, inplace = True) 
    formats = {'Energy': '{:3.1f}', 'Cross Section': '{:.3E}', 'SysErr': '{:.3E}','StatErr': '{:.3E}'}
    for col, f in formats.items():
        df4[col] = df4[col].map(lambda x: f.format(x))
#     if(sheet==1 or sheet==2):
#         df4=df4[::4]
    df4.to_csv(f'{particle}_{ang}.txt', index = False, header=True,sep="\t")
    df3.to_csv(f'{particle}_{ang}piderror.csv', index = False, header=True)
    return df,df3,df4

In [18]:
for ang in [20,25,30,35,40,45,50,55,60,65,70,75,80]:
#for ang in [20,25,55,65,80]:
    df,df2,df3=read_excel(f"Proton{ang}.xlsx",2,ang)

Proton20.xlsx
Proton20

C:\Users\udai\Anaconda3\lib\site-packages\ipykernel_launcher.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Proton25.xlsx
Proton25
Proton30.xlsx
Proton30
Proton35.xlsx
Proton35
Proton40.xlsx
Proton40
Proton45.xlsx
Proton45
Proton50.xlsx
Proton50
Proton55.xlsx
Proton55
Proton60.xlsx
Proton60
Proton65.xlsx
Proton65
Proton70.xlsx
Proton70
Proton75.xlsx
Proton75
Proton80.xlsx
Proton80

In [7]:
df3

   Energy Cross Section     SysErr    StatErr
4   180.0     9.971E-03  6.612E-03  3.305E-04
5   200.0     7.072E-03  4.481E-03  2.604E-04
6   220.0     4.722E-03  2.812E-03  1.688E-04
7   240.0     3.535E-03  2.061E-03  1.470E-04
8   260.0     2.558E-03  1.620E-03  1.124E-04
9   280.0     2.219E-03  1.396E-03  1.087E-04
10  300.0     1.736E-03  1.195E-03  8.608E-05
11  320.0     1.514E-03  1.152E-03  8.946E-05
12  340.0     1.204E-03  9.606E-04  8.253E-05
13  360.0     9.763E-04  8.300E-04  8.458E-05
14  380.0     1.109E-03  6.328E-04  7.396E-05

In [17]:
df2

   Energy  Cross Section  PIDerr     StatErr  EffError   SectorErr  SysErr
0     120         5.4352  6.3117  1.4807e-01    0.0044  8.8814e-03  6.3134
1     150         0.0276  0.0037  3.3348e-04    0.0323  5.4149e-04  0.0326
2     180         0.0101  0.0011  1.4801e-04    0.0072  3.0566e-04  0.0073
3     210         0.0061  0.0012  9.0204e-05    0.0059  1.4560e-04  0.0060
4     240         0.0025  0.0007  5.0864e-05    0.0023  4.5718e-05  0.0024

In [18]:
df3

  Energy Cross Section     SysErr    StatErr
0  120.0     5.435E+00  6.313E+00  1.481E-01
1  150.0     2.762E-02  3.256E-02  3.335E-04
2  180.0     1.014E-02  7.333E-03  1.480E-04
3  210.0     6.104E-03  5.986E-03  9.020E-05
4  240.0     2.512E-03  2.394E-03  5.086E-05